services:
  postgres:
    image: postgres:16-alpine
    container_name: secure_api_postgres
    #command: ["postgres", "-c", "timezone=UTC"]
    environment:
      POSTGRES_DB: secure_api
      POSTGRES_USER: secure_api
      POSTGRES_PASSWORD: secure_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
